openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /user:
    get:
      summary: Check if head Authorization works
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Successfull checked header
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
      tags: [ ]
  /user/login:
    post:
      summary: Login for users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
              example:
                user:
                  username: Tim119
                  password: sicheresPassword
      responses:
        200:
          description: Successfull loged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: Authorization failed
      tags: [ ]
  /user/logout:
    post:
      summary: Logout for users
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Successfull loged out
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
  /user/register:
    post:
      summary: Registation for new users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
              example:
                user:
                  username: Tim119
                  password: sicheresPassword1
      responses:
        200:
          description: Successfull registered and loged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        409:
          description: Please select a other username this one is used
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: This username is already used
      tags: [ ]
  /favorite:
    get:
      summary: show favorite
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Successfull checked header
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  data:
                    type: object
                    properties:
                      favorites:
                        type: array
                        items:
                          id:
                            type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                  data:
                    favorites: [ "5fbf7bebcbf1374sdfsd1233fa6ded41","123123123343tre34256049875023zuvntc3t4" ]

        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
      tags: [ ]
    post:
      summary: add favorite
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              example:
                id: dfgbsdf21389jfndkj
      responses:
        200:
          description: Successfull added favorite
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
      tags: [ ]
    delete:
      summary: remove favorite
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              example:
                id: dfgbsdf21389jfndkj
      responses:
        200:
          description: Successfull added favorite
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
      tags: [ ]
  /offer:
    get:
      summary: Get all offers
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Successfull loaded all offers
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  data:
                    type: object
                    properties:
                      offerlist:
                        type: array
                        items:
                          type: object
                          properties:
                            _name:
                              type: string
                            _description:
                              type: string
                            _size:
                              type: double
                            _brand:
                              type: string
                            _price:
                              type: double
                            _condition:
                              type: string
                            _created:
                              type: date
                            _ownerName:
                              type: string
                            _id:
                              type: string
                            _pickUpAdress:
                              type: object
                              properties:
                                _id:
                                  tpye: string
                                _streetName:
                                  type: string
                                _homeNumber:
                                  type: string
                                _postCode:
                                  type: string
                                _cityName:
                                  type: string

                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                  data:
                    offerlist:
                      - _id: 5fbf7bebcbf13743fa6ded41
                        _name: Testoffer1
                        _description: New Offer
                        _price: 9.1
                        _size: 7
                        _brand: Nike
                        _condition: New
                        _ownerName: TestUser
                        _created: 2020-11-26T09:56:59.929Z
                        _pickUpAddress:
                          _id: 5fd62b19fbefa6181053a9f1
                          _streetName: Wiesbaden
                          _homeNumber: 1
                          _postCode: 65185
                          _cityName: Wiesbaden

        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
      tags: [ ]
    post:
      summary: Create a new offer
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                offer:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    size:
                      type: double
                    brand:
                      type: string
                    price:
                      type: double
                    condition:
                      type: string
                      address:
                        type: object
                        properties:
                          streetName:
                            type: string
                          homeNumber:
                            type: string
                          postCode:
                            type: string
                          cityName:
                            type: string

              example:
                offer:
                  name: gread Sneaker
                  description: look nice
                  size: 9.5
                  brand: Nike
                  price: 125
                  condition: New
                  adress:
                    streetName: NiceStreet
                    homeNumber: 9
                    postCode: 65185
                    cityName: Wiesbaden
      responses:
        200:
          description: Successfull added a new offer
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
        500:
          description: Database problem
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: database failed to create ressource
      tags: [ ]
    delete:
      summary: Delete a offer
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              example:
                id: sfdgsdfger34t4dfdfg
      responses:
        200:
          description: Succesfull deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        403:
          description: you don't have permissions for that
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You are not permit to use that ressource
        404:
          description: Please add correct data
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: Can't find ressource
      tags: [ ]
  /chat:
    get:
      summary: Get all Chats of user
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Successfull checked header
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  data:
                    type: object
                    properties:
                      chatList:
                        type: array
                          items:
                            type: object
                            properties:
                              _subcriber:
                                type: array
                                  items:
                                    type: string
                              _id:
                                type: string
                              _messages:
                                type: array
                                  items:
                                    type: object
                                    properties:
                                      _senderId:
                                        type: string
                                      _message:
                                        tpye: string
                                      _chatId:
                                        tpye: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                  data:
                    chatList:
                      - _subcriber:
                          - "eyJhbGciasdasdasdadasdasd143"
                          - "eyJhbGciasdaasdasdsdasdadasd"
                        _id: 5fbf7bebcbf13743fa6ded41,
                        _messages:
                          - _senderId: "eyJhbGciasdasdasdad"
                            _message: "hallo Welt"
                            _chatId: "5fcb4c6615a1db0bd2abcec1"
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
      tags: [ ]
    post:
      summary: start a chat with someone
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subscriber:
                  type: string
              example:
                subscriber: "5fc3f54613865788857713e6"
      responses:
        200:
          description: Successfull checked header
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        404:
          description: Please add correct data
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
        409:
          description: Please select a other user pair
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: Users already chatted
        500:
          description: Database problem
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: database failed to create ressource
      tags: [ ]
  /chat/message:
    post:
      summary: Add message to chat
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chatId:
                  type: string
                message:
                  type: string
              example:
                chatId: "5fcb4c6615a1db0bd2abcec1"
                chatMessage: "Hallo Welt"
      responses:
        200:
          description: Successfull added message
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: Please add a valid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You body was not correct
        401:
          description: Authorization failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: you need a authorization header
        403:
          description: you don't have permissions for that
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: You are not permit to use that ressource
        404:
          description: Please add correct username
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: No user with this username found
        tags: [ ]
tags: [ ]
info:
  title: Sneakerverse api-documentation
  version: 0.0.0
  description: 'Documentation:'
